---

# For use with pre-commit.
# See usage instructions at http://pre-commit.com

- id: pluto_detect_files
  name: pluto detect-files
  description: Detect Kubernetes apiVersions in a directory
  entry: hooks/pluto/pluto_detect_files.sh
  language: script
  require_serial: true
  files: (\.yml|\.yaml)$
  args: []

- id: pluto_detect_helm
  name: pluto detect-helm
  description: Detect Kubernetes apiVersions in a helm release (in cluster)
  entry: hooks/pluto/pluto_detect_helm.sh
  language: script
  require_serial: true
  files: (\.yml|\.yaml)$
  args: []

- id: pluto_detect_api
  name: pluto detect-api-resources
  description: Detect Kubernetes apiVersions from an active cluster.
  entry: hooks/pluto/pluto_detect_api.sh
  language: script
  require_serial: true
  files: (\.yml|\.yaml)$
  args: []

- id: nova_search_updates
  name: nova finding
  description: A tool to check for updated chart releases
  entry: hooks/nova/nova_search_updates.sh
  language: script
  require_serial: true
  args: []

- id: popeye_scan
  name: popeye scanning
  description: Scans your Kubernetes clusters and reports potential resource issues
  entry: hooks/popeye/popeye_scan.sh
  language: script
  require_serial: true
  args: []

- id: kubescore_score
  name: kube-score
  description: Static code analysis for Kubernetes object definitions
  entry: hooks/kubescore/kubescore_score.sh
  language: script
  require_serial: true
  files: (\.yml|\.yaml)$
  args: []

- id: snyk_test
  name: snyk test
  description: Test dependencies for vulnerabilities with Snyk
  entry: hooks/snyk/snyk_test.sh
  language: script
  require_serial: true
  args: []

- id: snyk_container
  name: snyk container test
  description: Scan container images for vulnerabilities with Snyk
  entry: hooks/snyk/snyk_container.sh
  language: script
  require_serial: true
  args: []

- id: snyk_iac
  name: snyk iac test
  description: Scan Infrastructure as Code files for security issues with Snyk
  entry: hooks/snyk/snyk_iac.sh
  language: script
  require_serial: true
  files: (\.yml|\.yaml|\.tf|\.json)$
  args: []

- id: trivy_fs
  name: trivy filesystem scan
  description: Scan filesystem for vulnerabilities with Trivy
  entry: hooks/trivy/trivy_fs.sh
  language: script
  require_serial: true
  args: []

- id: trivy_image
  name: trivy image scan
  description: Scan container images for vulnerabilities with Trivy
  entry: hooks/trivy/trivy_image.sh
  language: script
  require_serial: true
  args: []

- id: checkov_scan
  name: checkov scan
  description: Scan Infrastructure as Code for security and compliance issues
  entry: hooks/checkov/checkov_scan.sh
  language: script
  require_serial: true
  files: (\.yml|\.yaml|\.tf|\.json|Dockerfile)$
  args: []
