---

# For use with pre-commit.
# See usage instructions at http://pre-commit.com

- id: pluto_detect_files
  name: pluto detect-files
  description: Search for deprecated Kubernetes API(s) in files
  entry: hooks/pluto/pluto_detect_files.sh
  language: script
  require_serial: true
  files: (\.yml|\.yaml)$
  args: []

- id: pluto_detect_helm
  name: pluto detect-helm
  description: Search for deprecated helm charts in Kubernetes
  entry: hooks/pluto/pluto_detect_helm.sh
  language: script
  require_serial: true
  files: (\.yml|\.yaml)$
  args: []

- id: pluto_detect_api
  name: pluto detect-helm
  description: Detect Kubernetes apiVersions from an active cluster.
  entry: hooks/pluto/pluto_detect_api.sh
  language: script
  require_serial: true
  files: (\.yml|\.yaml)$
  args: []

- id: nova_search_updates
  name: nova find
  description: A tool to check for updated chart releases
  entry: hooks/nova/nova_search_updates.sh
  language: script
  require_serial: true
  args: []

- id: popeye_scan
  name: popeye scanning
  description: Scans your Kubernetes clusters and reports potential resource issues
  entry: hooks/popeye/popeye_scan.sh
  language: script
  require_serial: true
  args: []
