default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: detect-private-key
    - id: end-of-file-fixer
