-   id: pluto_detect_files
    name: pluto detect-files
    description: Search for deprecated Kubernetes API(s) in files
    entry: hooks/pluto_detect_files.sh
    language: script
    require_serial: true
    files: (\.yml|\.yaml)$
    args: []
